sonar.projectKey=task-a
sonar.projectName=Task A - Blog API
sonar.sources=.
sonar.exclusions=node_modules/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_8be955bb8166b2ab4dd3365d2aaf460f6f399a95
sonar.javascript.lcov.reportPaths=coverage/lcov.info